services:
  backend_rds:
    image: 148761653308.dkr.ecr.eu-north-1.amazonaws.com/backend_rds:5fc614d
    ports:
      - "8001:8001"
    networks:
      - my_network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=mypostgres
      - DB_PASSWORD=mypassword1
      - DATABASE_URL=mydatabase.ctokg0ogebib.eu-north-1.rds.amazonaws.com
      - CORS_ALLOWED_ORIGINS=http://d8s5v5w0sk5z.cloudfront.net

  backend_redis:
    image: 148761653308.dkr.ecr.eu-north-1.amazonaws.com/backend_redis:5fc614d
    ports:
      - "8002:8002"
    networks:
      - my_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CORS_ALLOWED_ORIGINS=http://d8s5v5w0sk5z.cloudfront.net

networks:
  my_network:
    driver: bridge