services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: mypostgres
      POSTGRES_PASSWORD: mypassword1
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes:
      - redis_data:/data

  backend_rds:
    image: backend_rds:latest
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    networks:
      - my_network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=mypostgres
      - DB_PASSWORD=mypassword1
      - CORS_ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000

  backend_redis:
    image: backend_redis:latest
    ports:
      - "8002:8002"
    networks:
      - my_network
    environment:
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CORS_ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000 

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: